// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctfjwtvkdsuvtzsjlyss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0Zmp3dHZrZHN1dnR6c2pseXNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNzU0MzIsImV4cCI6MjA2MTY1MTQzMn0.Y8CN-2HA273m_nvrJuIRcjwzZWMbxjYPanP_Hj-IjCI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);